// Generated by Selenium IDE
package tests;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class DodavanjeStudentaSaPraznimMejlomTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void dodavanjeStudentaSaPraznimMejlom() throws InterruptedException {
		driver.get("http://localhost:4200/");
		driver.manage().window().setSize(new Dimension(1054, 800));
		Thread.sleep(3000);
		vars.put("t1", driver.findElement(By.xpath("/html/body/app-root/div/app-student-list/div[1]/div[2]/div/div[4]"))
				.getText().split(" ")[5]);
		driver.findElement(By.linkText("Add Student")).click();
		Thread.sleep(3000);

		driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
		driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[1]/input"))
				.sendKeys("marko");
		Thread.sleep(3000);
		driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).click();

		{
			WebElement dropdown = driver.findElement(By.cssSelector(".ng-untouched"));
			dropdown.findElement(By.xpath("//option[. = 'B-Tech']")).click();
		}
		driver.findElement(By.cssSelector(".btn-success")).click();
		Thread.sleep(3000);
		driver.findElement(By.linkText("View Student")).click();
		Thread.sleep(3000);
		vars.put("t2", driver.findElement(By.xpath("/html/body/app-root/div/app-student-list/div[1]/div[2]/div/div[4]"))
				.getText().split(" ")[5]);
		assertEquals(vars.get("t2").toString(), vars.get("t1").toString());
	}
}
