package tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class DodavanjeValidnogStudentaTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void dodavanjeValidnogStudenta() throws InterruptedException {
		driver.get("http://localhost:4200/");
		driver.manage().window().setSize(new Dimension(1057, 800));
		Thread.sleep(2000);
		vars.put("t1", driver.findElement(By.xpath("/html/body/app-root/div/app-student-list/div[1]/div[2]/div/div[4]"))
				.getText().split(" ")[5] + 1);

		driver.findElement(By.linkText("Add Student")).click();
		driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
		driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[1]/input"))
				.sendKeys("Tijana");
		driver.findElement(By.cssSelector(".form-group:nth-child(2)")).click();
		driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).click();
		driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[2]/input"))
				.sendKeys("tijana@google.com");
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".ng-untouched"));
			dropdown.findElement(By.xpath("//option[. = 'BCA']")).click();
		}
		driver.findElement(By.cssSelector(".btn-success")).click();
		Thread.sleep(3000);
		driver.findElement(By.linkText("View Student")).click();
		{
			WebElement element = driver.findElement(By.linkText("View Student"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		driver.findElement(By.name("DataTables_Table_1_length")).click();
		{
			WebElement dropdown = driver.findElement(By.name("DataTables_Table_1_length"));
			dropdown.findElement(By.xpath("//option[. = '16']")).click();
		}
		Thread.sleep(2000);
		List<WebElement> rows = driver
				.findElements(By.xpath("/html/body/app-root/div/app-student-list/div[1]/div[2]/div/table/tbody/tr"));
		boolean studentFound = false;

		for (WebElement row : rows) {
			List<WebElement> cells = row.findElements(By.tagName("td"));

			if (cells.size() >= 3 && "Tijana".equals(cells.get(0).getText())
					&& "tijana@google.com".equals(cells.get(1).getText()) && "BCA".equals(cells.get(2).getText())) {
				studentFound = true;
				break;
			}
		}

		assertTrue("Student sa odgovarajućim kredencijalima nije pronađen.", studentFound);
	}

}
